### ISSUE TITLE
Steffengy comments

### ISSUE THREAD

**Issue by themandalore** [tellor-io/tellorFlex#17]
@tkernell 

 initial steffengy comments:  
* depositStake: no way to partially use lockedBalance (e.g. always have to either fully used locked or deposit full amount - desired from gas usage?)
* slashReporter: 
"_staker.lockedBalance + _staker.stakedBalance >= stakeAmount" branch doesnt look right to me:
Assuming lockedBalance = 500, stakeAmount = 100, stakedBalance=0:
0 -= 100 - 500 ; multiple overflows leading slashReporter to revert.
* submitValue: That stake balance stacking effect is interesting,
reduces barrier for "reporter centralization" a tiny bit more though.

**Comment by tkernell** [comment]
- slashReporter: doesn't the first branch `if (_staker.lockedBalance >= stakeAmount)` handle this issue?
